# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a706dbebdcb35cc572db7941ed20a653eb9806a559e59d6ce63288bc58ff46e078399c23cc2bced54884f568bcbf05494c9a0e9805207e2c5bedb291049b86ac

test:
  secret_key_base: d4855164ffde3ac2db22030b174ba4b8dbbd344e1a6aa770ff33a4dbbbee1bbf6398e0aede4705d8f00a9f744312fc4d91aed52fa0a4e5cae43bd02d0ab8da9b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
